---
title: "[WELCOME]{.clr-white .r-fit-text}"
subtitle: "[SARA Data Science Bootcamp <br> 3-7 Mar 2025 $\\cdot$ Sonipat (HR)]{.clr-white .r-fit-text}"
#author: "[SARA Institute of Data Science, Sonipat, Haryana, India]{.clr-white .r-fit-text}"
page-title: "Welcome"
format: revealjs
progress: true
controls: true
slide-number: true
scrollable: true
menu: true
logo: images/logo-sara.png
#bibliography: references.bib
theme: style.scss
title-slide-attributes: 
  data-background-image: "https://images.unsplash.com/photo-1593248196138-bad1a611a766?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  data-background-size: cover
---

## {background-color="black"}

{{< revealjs file="https://sara-intro.netlify.app/#/section" height="600px" class="ratio ratio-16x9" >}}

# {background-image=images/march-workshop-promo.png background-size=contain background-color="black"}

##  {background-image="images/flyer-march.png" background-position="right" background-size="50%" background-color="black"}

:::: {.columns}

::: {.column width="40%"}
<br>

[SARA <br>Data <br>Science <br>Bootcamp]{.r-fit-text}
:::

::: {.column width="50%"}

:::

::::

## Goals

1. Build your personal website.

1. Write thesis/book/article using data science tools.

1. Prepare slides using data science tools.

## Logistics:

-   Don't be late for the class \~5 minutes

- Ask questions, clear your doubts.

-   Classes will be in the Mata Ramabai Auditorium, 1st Floor, Dr. Ambedkar Bhawan.

-   [**You will have to use your own internet.**]{.clr-blue}

-   Be kind to each and everyone.

## Daily Schedule:

::: panel-tabset
### {{< fa utensils >}} Food

| Time                 | Activity  |
|----------------------|-----------|
| 08:00 AM to 08:45 AM | Breakfast |
| 01:00 PM to 02:00 PM | Lunch     |
| 07:30 PM to 08:30 PM | Dinner    |


### {{< fa laptop >}} Lectures

::: .r-fit-text

| Time                 | Activity    |
|----------------------|-------------|
| 09:30 AM to 11:00 AM | Class 1     |
| {{< fa mug-hot >}}    | Discussion  |
| 11:30 AM to 01:00 PM | Class 2     |
| {{< fa utensils >}}    | Lunch  |
| 02:00 PM to 03:30 PM | Class 3     |
| {{< fa mug-hot >}}    | Discussion  |
| 04:00 PM to 05:30 PM | Class 4     |

:::

:::

## Important Mobile Numbers:

| Name                                                | Mobile |
|-------------------------------------------|----------------------|
| Mr. Raj Pal (Supervisor, Dr. Ambedkar Bhawan)      | 93063 42596   |
| SARA Institute Office                              | 925 315 2024  |
| Dr. Ajay Kumar (Ex. Director, SARA)                | 88868 10879   |
| Dr. Kiran Koli (Director, SARA)                    | 81680 60500   |
| Mr. Satyawan Bhatia <br>(President, Dr. Ambedkar Bhawan) | 94165 40721   |

## Overview

-   Around **30 hours** of residential teaching for 5 days.

-   [**Open for All, Free for All.**]{.clr-blue}

- **Feedback** on the last day of the event.

-   **Thank You Ceremony!** on Friday, 07 MAR 2024, 4 PM

- **e-Certificate** of the participation via email within a week.

## Course Website {background-color="black"}

<https://sara-course-quarto.netlify.app/>


{{< revealjs file="https://sara-course-quarto.netlify.app/" height="600px" class="ratio ratio-16x9" full-screen-link=false >}}